### ISSUE TITLE
Output is fast. 

### ISSUE THREAD

**Issue by beave** [swenson/ttyrec2gif#3]
Overall, this routine works really well.   The fact that it isn't taking screenshots & doesn't require a GUI is a plus.  Thanks.

One thing that I've noticed is the output seems about (guesstimating) twice as fast as it should be.  

Is it possible timing isn't being correctly converted?  Thanks.

**Comment by swenson** [comment]
It's speed up on purpose, to make it seem more lively. There is a `--speedup` option you can supply to control this -- it defaults to `5`, for 5x faster than real-time.

**Comment by beave** [comment]
Just tested with --speed 1.0 and that worked like a charm.  Thank you very much.  I'm going to close this.

**Comment by swenson** [comment]
No problem!
